name: go-test
on: [push]
jobs:
  go-test:
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go_version: ['1.15.0', '1.16.0']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '~${{ matrix.go_version }}'
      - run: go test ./...
